### PR TITLE
Fix ListField(<ItemField>) for Union and Remove

### PR DESCRIPTION
**Pull request by ADR-007**
- Use Field as a default field class for ListField nested field to simplify the code base
- Fix ArrayUnion and ArrayRemove for ListField with nested field

### CODE REVIEW

**Comment by ADR-007** [comment]
Btw. why do we have `if self.model_cls._meta.to_lowercase:` in `Field` and `MapField`? Does anybody really use it? What is the use-case?

**Comment by AxeemHaider** [comment]
This is just because Firestore is case sensitive and I just provide and extra option to make text lowercase. So, you can easily find by text when you search. It's ok if you removed it from `ListField` I think no one is using it in `ListField` But I think it's good to have in `TextField`

**Comment by ADR-007** [comment]
> This is just because Firestore is case sensitive and I just provide and extra option to make text lowercase. So, you can easily find by text when you search. It's ok if you removed it from `ListField` I think no one is using it in `ListField` But I think it's good to have in `TextField`

It still works in ListField. The logic is in Field class. I just removed the code duplication

**Comment by AxeemHaider** [comment]
Yes, I think it should be only in `TextField` because `lowercase` property is related to `string`

**Pull request merged**
