### PR TITLE
move _create_time _update_time to a model

### PR DESCRIPTION
**Pull request by kulik0v**

### CODE REVIEW

**Comment by kulik0v** [comment]
fixing issue #141

**Comment by AxeemHaider** [comment]
Thanks for finding this issue and solving it. PR merged update fireO package

**Comment by kulik0v** [comment]
> Thanks for finding this issue and solving it. PR merged update fireO package

@AxeemHaider thank you too.

Fireo is a great project! :)

**Comment by kulik0v** [comment]
@AxeemHaider i think we have the same issue saving doc.reference.
See 
`model._meta.set_reference_doc(doc.reference)`
few lines above my fix.

But I didn't debug it, cant say for sure.

**Pull request merged**
